# Form implementation generated from reading ui file 'BoxFilterComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BoxFilterComponentWidget(object):
    def setupUi(self, BoxFilterComponentWidget):
        BoxFilterComponentWidget.setObjectName("BoxFilterComponentWidget")
        BoxFilterComponentWidget.resize(320, 253)
        self.verticalLayout = QtWidgets.QVBoxLayout(BoxFilterComponentWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enableWidget = QtWidgets.QWidget(parent=BoxFilterComponentWidget)
        self.enableWidget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.enableWidget.setObjectName("enableWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.enableWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enableButton = QtWidgets.QRadioButton(parent=self.enableWidget)
        self.enableButton.setChecked(True)
        self.enableButton.setObjectName("enableButton")
        self.horizontalLayout_2.addWidget(self.enableButton)
        self.verticalLayout.addWidget(self.enableWidget)
        self.kernalSizeWidget = QtWidgets.QWidget(parent=BoxFilterComponentWidget)
        self.kernalSizeWidget.setObjectName("kernalSizeWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.kernalSizeWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.kernalSizeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.filter = QtWidgets.QLabel(parent=self.kernalSizeWidget)
        self.filter.setText("")
        self.filter.setObjectName("filter")
        self.verticalLayout_2.addWidget(self.filter)
        self.openfile = QtWidgets.QPushButton(parent=self.kernalSizeWidget)
        self.openfile.setObjectName("openfile")
        self.verticalLayout_2.addWidget(self.openfile)
        self.verticalLayout.addWidget(self.kernalSizeWidget)

        self.retranslateUi(BoxFilterComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(BoxFilterComponentWidget)

    def retranslateUi(self, BoxFilterComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        BoxFilterComponentWidget.setWindowTitle(_translate("BoxFilterComponentWidget", "Form"))
        self.enableButton.setText(_translate("BoxFilterComponentWidget", "Enable"))
        self.label.setText(_translate("BoxFilterComponentWidget", "当前Filter:"))
        self.openfile.setText(_translate("BoxFilterComponentWidget", "打开filter文件"))
