# Form implementation generated from reading ui file 'GradientFilterComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GradientFiterComponentWidget(object):
    def setupUi(self, GradientFiterComponentWidget):
        GradientFiterComponentWidget.setObjectName("GradientFiterComponentWidget")
        GradientFiterComponentWidget.resize(180, 301)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GradientFiterComponentWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.enableWidget = QtWidgets.QWidget(parent=GradientFiterComponentWidget)
        self.enableWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.enableWidget.setObjectName("enableWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.enableWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.enableButton = QtWidgets.QRadioButton(parent=self.enableWidget)
        self.enableButton.setChecked(True)
        self.enableButton.setObjectName("enableButton")
        self.horizontalLayout_3.addWidget(self.enableButton)
        self.verticalLayout_3.addWidget(self.enableWidget)
        self.widget = QtWidgets.QWidget(parent=GradientFiterComponentWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMaximumSize(QtCore.QSize(40130, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Laplacian = QtWidgets.QRadioButton(parent=self.widget_3)
        self.Laplacian.setChecked(True)
        self.Laplacian.setObjectName("Laplacian")
        self.verticalLayout_2.addWidget(self.Laplacian)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Fore = QtWidgets.QRadioButton(parent=self.widget_4)
        self.Fore.setChecked(True)
        self.Fore.setObjectName("Fore")
        self.horizontalLayout_2.addWidget(self.Fore)
        self.Eight = QtWidgets.QRadioButton(parent=self.widget_4)
        self.Eight.setObjectName("Eight")
        self.horizontalLayout_2.addWidget(self.Eight)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.Prewitt = QtWidgets.QRadioButton(parent=self.widget_3)
        self.Prewitt.setObjectName("Prewitt")
        self.verticalLayout_2.addWidget(self.Prewitt)
        self.Robert = QtWidgets.QRadioButton(parent=self.widget_3)
        self.Robert.setObjectName("Robert")
        self.verticalLayout_2.addWidget(self.Robert)
        self.Sobel = QtWidgets.QRadioButton(parent=self.widget_3)
        self.Sobel.setObjectName("Sobel")
        self.verticalLayout_2.addWidget(self.Sobel)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.widget)

        self.retranslateUi(GradientFiterComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(GradientFiterComponentWidget)

    def retranslateUi(self, GradientFiterComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        GradientFiterComponentWidget.setWindowTitle(_translate("GradientFiterComponentWidget", "Form"))
        self.enableButton.setText(_translate("GradientFiterComponentWidget", "Enable"))
        self.label.setText(_translate("GradientFiterComponentWidget", "Gradient FilterType"))
        self.Laplacian.setText(_translate("GradientFiterComponentWidget", "Laplacian"))
        self.Fore.setText(_translate("GradientFiterComponentWidget", "Fore"))
        self.Eight.setText(_translate("GradientFiterComponentWidget", "Eight"))
        self.Prewitt.setText(_translate("GradientFiterComponentWidget", "Prewitt"))
        self.Robert.setText(_translate("GradientFiterComponentWidget", "Robert"))
        self.Sobel.setText(_translate("GradientFiterComponentWidget", "Sobel"))
