# Form implementation generated from reading ui file 'ImageCaculateComponent.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageCaculateComponent(object):
    def setupUi(self, ImageCaculateComponent):
        ImageCaculateComponent.setObjectName("ImageCaculateComponent")
        ImageCaculateComponent.resize(300, 166)
        ImageCaculateComponent.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ImageCaculateComponent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=ImageCaculateComponent)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.currentImg = QtWidgets.QTextBrowser(parent=self.widget_2)
        self.currentImg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.currentImg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.currentImg.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.currentImg.setObjectName("currentImg")
        self.horizontalLayout.addWidget(self.currentImg)
        self.verticalLayout.addWidget(self.widget_2)
        self.openfile = QtWidgets.QPushButton(parent=self.widget)
        self.openfile.setObjectName("openfile")
        self.verticalLayout.addWidget(self.openfile)
        self.verticalLayout_2.addWidget(self.widget)
        self.attributeWidget = QtWidgets.QWidget(parent=ImageCaculateComponent)
        self.attributeWidget.setObjectName("attributeWidget")
        self.verticalLayout_2.addWidget(self.attributeWidget)

        self.retranslateUi(ImageCaculateComponent)
        QtCore.QMetaObject.connectSlotsByName(ImageCaculateComponent)

    def retranslateUi(self, ImageCaculateComponent):
        _translate = QtCore.QCoreApplication.translate
        ImageCaculateComponent.setWindowTitle(_translate("ImageCaculateComponent", "Form"))
        self.label.setText(_translate("ImageCaculateComponent", "Other Image"))
        self.label_2.setText(_translate("ImageCaculateComponent", "current image:"))
        self.openfile.setText(_translate("ImageCaculateComponent", "Open File"))
