# Form implementation generated from reading ui file 'ImageChannelComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageChannelComponentWidget(object):
    def setupUi(self, ImageChannelComponentWidget):
        ImageChannelComponentWidget.setObjectName("ImageChannelComponentWidget")
        ImageChannelComponentWidget.resize(428, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageChannelComponentWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enableWidget = QtWidgets.QWidget(parent=ImageChannelComponentWidget)
        self.enableWidget.setObjectName("enableWidget")
        self.verticalLayout.addWidget(self.enableWidget)
        self.R = RadioScrollWidget(parent=ImageChannelComponentWidget)
        self.R.setObjectName("R")
        self.verticalLayout.addWidget(self.R)
        self.G = RadioScrollWidget(parent=ImageChannelComponentWidget)
        self.G.setObjectName("G")
        self.verticalLayout.addWidget(self.G)
        self.B = RadioScrollWidget(parent=ImageChannelComponentWidget)
        self.B.setObjectName("B")
        self.verticalLayout.addWidget(self.B)
        self.A = RadioScrollWidget(parent=ImageChannelComponentWidget)
        self.A.setObjectName("A")
        self.verticalLayout.addWidget(self.A)

        self.retranslateUi(ImageChannelComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageChannelComponentWidget)

    def retranslateUi(self, ImageChannelComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        ImageChannelComponentWidget.setWindowTitle(_translate("ImageChannelComponentWidget", "Form"))
from widgets.utils.RadioScrollWidget import RadioScrollWidget
