# Form implementation generated from reading ui file 'KMeansThresholdingComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KMeansThresholdingComponentWidget(object):
    def setupUi(self, KMeansThresholdingComponentWidget):
        KMeansThresholdingComponentWidget.setObjectName("KMeansThresholdingComponentWidget")
        KMeansThresholdingComponentWidget.resize(320, 240)
        self.widget = QtWidgets.QWidget(parent=KMeansThresholdingComponentWidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 302, 94))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.enable = QtWidgets.QRadioButton(parent=self.widget)
        self.enable.setChecked(True)
        self.enable.setObjectName("enable")
        self.verticalLayout.addWidget(self.enable)
        self.widget_2 = QtWidgets.QWidget(parent=KMeansThresholdingComponentWidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 120, 302, 122))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.k = QtWidgets.QSpinBox(parent=self.widget_3)
        self.k.setMinimum(1)
        self.k.setMaximum(10)
        self.k.setProperty("value", 2)
        self.k.setObjectName("k")
        self.horizontalLayout.addWidget(self.k)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(KMeansThresholdingComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(KMeansThresholdingComponentWidget)

    def retranslateUi(self, KMeansThresholdingComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        KMeansThresholdingComponentWidget.setWindowTitle(_translate("KMeansThresholdingComponentWidget", "Form"))
        self.label.setText(_translate("KMeansThresholdingComponentWidget", "是否启用"))
        self.enable.setText(_translate("KMeansThresholdingComponentWidget", "Enable"))
        self.label_2.setText(_translate("KMeansThresholdingComponentWidget", "分类个数"))
        self.label_3.setText(_translate("KMeansThresholdingComponentWidget", "数量："))
