# Form implementation generated from reading ui file 'MirrorComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MirrorComponentWidget(object):
    def setupUi(self, MirrorComponentWidget):
        MirrorComponentWidget.setObjectName("MirrorComponentWidget")
        MirrorComponentWidget.resize(320, 240)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MirrorComponentWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=MirrorComponentWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.enable = QtWidgets.QRadioButton(parent=self.widget)
        self.enable.setChecked(True)
        self.enable.setObjectName("enable")
        self.verticalLayout.addWidget(self.enable)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=MirrorComponentWidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.x = QtWidgets.QRadioButton(parent=self.widget_2)
        self.x.setChecked(True)
        self.x.setAutoExclusive(False)
        self.x.setObjectName("x")
        self.verticalLayout_2.addWidget(self.x)
        self.y = QtWidgets.QRadioButton(parent=self.widget_2)
        self.y.setAutoExclusive(False)
        self.y.setObjectName("y")
        self.verticalLayout_2.addWidget(self.y)
        self.verticalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(MirrorComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(MirrorComponentWidget)

    def retranslateUi(self, MirrorComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        MirrorComponentWidget.setWindowTitle(_translate("MirrorComponentWidget", "Form"))
        self.label.setText(_translate("MirrorComponentWidget", "是否启用"))
        self.enable.setText(_translate("MirrorComponentWidget", "Enable"))
        self.label_2.setText(_translate("MirrorComponentWidget", "类别"))
        self.x.setText(_translate("MirrorComponentWidget", "X"))
        self.y.setText(_translate("MirrorComponentWidget", "Y"))
