# Form implementation generated from reading ui file 'NamedSilder.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NamedSilder(object):
    def setupUi(self, NamedSilder):
        NamedSilder.setObjectName("NamedSilder")
        NamedSilder.resize(320, 36)
        self.horizontalLayout = QtWidgets.QHBoxLayout(NamedSilder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(parent=NamedSilder)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.slider = QtWidgets.QSlider(parent=NamedSilder)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.val = QtWidgets.QLabel(parent=NamedSilder)
        self.val.setObjectName("val")
        self.horizontalLayout.addWidget(self.val)

        self.retranslateUi(NamedSilder)
        QtCore.QMetaObject.connectSlotsByName(NamedSilder)

    def retranslateUi(self, NamedSilder):
        _translate = QtCore.QCoreApplication.translate
        NamedSilder.setWindowTitle(_translate("NamedSilder", "Form"))
        self.name.setText(_translate("NamedSilder", "name"))
        self.val.setText(_translate("NamedSilder", "val"))
