# Form implementation generated from reading ui file 'SaltAndPepperNoiseComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SaltAndPepperNoiseComponentWidget(object):
    def setupUi(self, SaltAndPepperNoiseComponentWidget):
        SaltAndPepperNoiseComponentWidget.setObjectName("SaltAndPepperNoiseComponentWidget")
        SaltAndPepperNoiseComponentWidget.resize(320, 188)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(SaltAndPepperNoiseComponentWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(parent=SaltAndPepperNoiseComponentWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.enable = QtWidgets.QRadioButton(parent=self.widget)
        self.enable.setChecked(True)
        self.enable.setObjectName("enable")
        self.verticalLayout.addWidget(self.enable)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(parent=SaltAndPepperNoiseComponentWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.salt = QtWidgets.QCheckBox(parent=self.widget_2)
        self.salt.setChecked(True)
        self.salt.setObjectName("salt")
        self.verticalLayout_2.addWidget(self.salt)
        self.pepper = QtWidgets.QCheckBox(parent=self.widget_2)
        self.pepper.setChecked(True)
        self.pepper.setObjectName("pepper")
        self.verticalLayout_2.addWidget(self.pepper)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.widget_3)

        self.retranslateUi(SaltAndPepperNoiseComponentWidget)
        QtCore.QMetaObject.connectSlotsByName(SaltAndPepperNoiseComponentWidget)

    def retranslateUi(self, SaltAndPepperNoiseComponentWidget):
        _translate = QtCore.QCoreApplication.translate
        SaltAndPepperNoiseComponentWidget.setWindowTitle(_translate("SaltAndPepperNoiseComponentWidget", "Form"))
        self.label.setText(_translate("SaltAndPepperNoiseComponentWidget", "是否启用"))
        self.enable.setText(_translate("SaltAndPepperNoiseComponentWidget", "Enable"))
        self.label_2.setText(_translate("SaltAndPepperNoiseComponentWidget", "噪声种类"))
        self.salt.setText(_translate("SaltAndPepperNoiseComponentWidget", "盐噪声"))
        self.pepper.setText(_translate("SaltAndPepperNoiseComponentWidget", "胡椒噪声"))
