# Form implementation generated from reading ui file 'SortedFilterComponentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SortedFilterWidget(object):
    def setupUi(self, SortedFilterWidget):
        SortedFilterWidget.setObjectName("SortedFilterWidget")
        SortedFilterWidget.resize(320, 144)
        self.verticalLayout = QtWidgets.QVBoxLayout(SortedFilterWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enableWidget = QtWidgets.QWidget(parent=SortedFilterWidget)
        self.enableWidget.setObjectName("enableWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.enableWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enableButton = QtWidgets.QRadioButton(parent=self.enableWidget)
        self.enableButton.setChecked(True)
        self.enableButton.setObjectName("enableButton")
        self.horizontalLayout_2.addWidget(self.enableButton)
        self.verticalLayout.addWidget(self.enableWidget)
        self.FilterTypeWidget = QtWidgets.QWidget(parent=SortedFilterWidget)
        self.FilterTypeWidget.setObjectName("FilterTypeWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FilterTypeWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min = QtWidgets.QRadioButton(parent=self.FilterTypeWidget)
        self.min.setObjectName("min")
        self.horizontalLayout.addWidget(self.min)
        self.mid = QtWidgets.QRadioButton(parent=self.FilterTypeWidget)
        self.mid.setObjectName("mid")
        self.horizontalLayout.addWidget(self.mid)
        self.max = QtWidgets.QRadioButton(parent=self.FilterTypeWidget)
        self.max.setChecked(True)
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.verticalLayout.addWidget(self.FilterTypeWidget)
        self.kernalSizeWidget = QtWidgets.QWidget(parent=SortedFilterWidget)
        self.kernalSizeWidget.setObjectName("kernalSizeWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.kernalSizeWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.kernalSizeWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=self.kernalSizeWidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout.addWidget(self.kernalSizeWidget)

        self.retranslateUi(SortedFilterWidget)
        QtCore.QMetaObject.connectSlotsByName(SortedFilterWidget)

    def retranslateUi(self, SortedFilterWidget):
        _translate = QtCore.QCoreApplication.translate
        SortedFilterWidget.setWindowTitle(_translate("SortedFilterWidget", "Form"))
        self.enableButton.setText(_translate("SortedFilterWidget", "Enable"))
        self.min.setText(_translate("SortedFilterWidget", "MinFilter"))
        self.mid.setText(_translate("SortedFilterWidget", "MidFilter"))
        self.max.setText(_translate("SortedFilterWidget", "MaxFilter"))
        self.label.setText(_translate("SortedFilterWidget", "KernelSize："))
