# Form implementation generated from reading ui file 'Ui_RadioScrollWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RadioScrollWidget(object):
    def setupUi(self, RadioScrollWidget):
        RadioScrollWidget.setObjectName("RadioScrollWidget")
        RadioScrollWidget.resize(320, 60)
        self.horizontalLayout = QtWidgets.QHBoxLayout(RadioScrollWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(parent=RadioScrollWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.slider = QtWidgets.QSlider(parent=RadioScrollWidget)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.label_2 = QtWidgets.QLabel(parent=RadioScrollWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.val = QtWidgets.QLabel(parent=RadioScrollWidget)
        self.val.setObjectName("val")
        self.horizontalLayout.addWidget(self.val)

        self.retranslateUi(RadioScrollWidget)
        QtCore.QMetaObject.connectSlotsByName(RadioScrollWidget)

    def retranslateUi(self, RadioScrollWidget):
        _translate = QtCore.QCoreApplication.translate
        RadioScrollWidget.setWindowTitle(_translate("RadioScrollWidget", "Form"))
        self.radioButton.setText(_translate("RadioScrollWidget", "text"))
        self.label_2.setText(_translate("RadioScrollWidget", "val:"))
        self.val.setText(_translate("RadioScrollWidget", "0"))
